In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#  Reading the dataset to python environment.

In [5]:
df = pd.read_excel(r"E:\Data Science\Assignments\Assignment-5\iris.xls")

In [3]:
df.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

# Doing the necessary pre-processing steps.

In [6]:
df.shape

(150, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [8]:
df.isna().sum()

SL                7
SW                6
PL                6
PW                0
Classification    0
dtype: int64

### FIlling Missing value with median

In [9]:
df['SL'].fillna(round(df['SL'].median(),1),inplace=True)

In [10]:
df.SL

0      5.1
1      4.9
2      5.8
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SL, Length: 150, dtype: float64

In [11]:
df['SW'].fillna(round(df['SW'].median(),1),inplace=True)
df['PL'].fillna(round(df['PL'].median(),1),inplace=True)

In [12]:
df.isna().sum()

SL                0
SW                0
PL                0
PW                0
Classification    0
dtype: int64

### Encoding the data

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Classification']= le.fit_transform(df['Classification'])

In [14]:
df

SL   SW   PL   PW  Classification
0    5.1  3.5  1.4  0.2               0
1    4.9  3.0  1.4  0.2               0
2    5.8  3.2  1.3  0.2               0
3    4.6  3.1  1.5  0.2               0
4    5.0  3.6  1.4  0.2               0
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3               2
146  6.3  2.5  5.0  1.9               2
147  6.5  3.0  4.3  2.0               2
148  6.2  3.4  5.4  2.3               2
149  5.9  3.0  5.1  1.8               2

[150 rows x 5 columns]

In [15]:
x = df.drop('Classification',axis=1)
y = df['Classification']

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2,random_state= 42) 

In [17]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(x_train,y_train)

In [18]:
predictions = model.predict(x_test)

In [19]:
from sklearn.metrics import mean_squared_error,r2_score
print ('MSE =',mean_squared_error(y_test,predictions))
print('R squared value = ',r2_score(y_test,predictions))

MSE = 0.03663458415102101
R squared value =  0.9475816760955185


### Logistic Regression Model

In [20]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
model = lr.fit(x_train,y_train)

In [21]:
y_predictions = model.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [23]:
confusion_matrix(y_test,y_predictions)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [24]:
print('accuracy is: ',round(accuracy_score(y_test,y_predictions),4))

accuracy is:  1.0


### Desicion Tree

In [25]:
from sklearn.tree import DecisionTreeClassifier
dt_clf = DecisionTreeClassifier()
dt_clf.fit(x_train,y_train)

DecisionTreeClassifier()

In [26]:
y_pred = dt_clf.predict(x_test)

In [27]:
print('accuracy is: ',accuracy_score(y_test,y_pred))

accuracy is:  1.0


In [28]:
print(confusion_matrix(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


### SVM

In [29]:
from sklearn.svm import SVC
svmclf = SVC(kernel = 'linear')
svmclf.fit(x_train,y_train)

SVC(kernel='linear')

In [30]:
y_pred = svmclf.predict(x_test)

In [31]:
print('accuracy is: ',accuracy_score(y_test,y_pred))

accuracy is:  1.0


In [32]:
print(confusion_matrix(y_test,y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


### Random Forest Algorithm

In [33]:
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier()
rf_clf.fit(x_train,y_train)

RandomForestClassifier()

In [36]:
y_pred = rf_clf.predict(x_test)

In [37]:
print('accuracy is: ',accuracy_score(y_test,y_pred))

accuracy is:  1.0


Considering accuracy values of all the models, Decision tree And Random Forest models have the best accuracy